Name=(input("Enter your name:"))
Age=(input("Enter your age:"))
Father_name=(input("Enter your father name:"))
Mother_name=(input("Enter your mother name:"))
Occupation=(input("Enter your occupation:"))
University_name=(input("Enter your university name:"))
Level=(input("Enter your level:"))
Email=(input("Enter your email:"))
Address=(input("Enter your address:"))

print(Name)
print(Age)
print(Father_name)
print(Mother_name)
print(Occupation)
print(University_name)
print(Level)
print(Email)
print(Address)